CREATE USER JARMU_NYILVANTARTO
IDENTIFIED BY 12345678;
ALTER USER JARMU_NYILVANTARTO DEFAULT tablespace users; 
ALTER USER JARMU_NYILVANTARTO QUOTA UNLIMITED ON USERS;

grant CREATE session TO JARMU_NYILVANTARTO;
grant CREATE PROCEDURE TO JARMU_NYILVANTARTO;
grant CREATE TABLE TO JARMU_NYILVANTARTO;
grant CREATE view TO JARMU_NYILVANTARTO;
grant CREATE sequence TO JARMU_NYILVANTARTO;
grant CREATE TRIGGER TO JARMU_NYILVANTARTO;
grant CREATE TYPE TO JARMU_NYILVANTARTO;
